#!/usr/bin/env python3

from simplemenu import *

menu = SimpleMenu('Title')
menu.add_element('com1', SMCommand, 'Command 1')
menu.add_element('com2', SMCommand, 'Command 2')
menu.add_element('com3', SMCommand, 'Command 3')
menu.add_element('com4', SMCommand, 'Command 4')
menu.add_element('com5', SMCommand, 'Command 5')
menu.add_element('sub1', SimpleMenu, 'Submenu 1')
menu.sub1.add_element('com3', SMCommand, 'Command 3')
menu.sub1.add_element('rad1', SMRadio, 'Radio 1', 'rgA')
menu.sub1.add_element('rad2', SMRadio, 'Radio 2', 'rgA')
menu.sub1.add_element('sub2', SimpleMenu, 'Submenu 2')
menu.sub1.sub2.add_element('chb1', SMCheckBox, 'Checkbox 1')
menu.sub1.sub2.add_element('chb2', SMCheckBox, 'Checkbox 2')
menu.show_tree(True)
print('\n')
print(menu.get_active_view())
menu.move_up()
print(menu.get_active_view())
menu.move_up()
print(menu.get_active_view())
menu.move_up()
print(menu.get_active_view())
menu.move_up()
print(menu.get_active_view())
menu.move_up()
print(menu.get_active_view())
menu.move_up()
print(menu.get_active_view())
menu.move_up()
print(menu.get_active_view())
menu.move_up()
print(menu.get_active_view())
print("\n")
print(menu)
print(menu.sub1)
print(menu.get_active_level())
print(menu.get_active_view())
menu.move_inside('sub1')
print(menu.get_active_level())
print(menu.get_active_view())
menu.move_back()
print(menu.get_active_level())
print(menu.get_active_view())
