#!/usr/bin/env python3


from simplemenu import *


if __name__ == "__main__":
    menu = SimpleMenu('Title')
    menu.addElement('com1', SMCommand, 'Command 1')
    menu.addElement('com2', SMCommand, 'Command 2')
    menu.addElement('com3', SMCommand, 'Command 3')
    menu.addElement('com4', SMCommand, 'Command 4')
    menu.addElement('com5', SMCommand, 'Command 5')
    menu.addElement('sub1', SimpleMenu, 'Submenu 1')
    menu.sub1.addElement('com3', SMCommand, 'Command 3')
    menu.sub1.addElement('rad1', SMRadio, 'Radio 1', 'rgA')
    menu.sub1.addElement('rad2', SMRadio, 'Radio 2', 'rgA')
    menu.sub1.addElement('sub2', SimpleMenu, 'Submenu 2')
    menu.sub1.sub2.addElement('chb1', SMCheckBox, 'Checkbox 1')
    menu.sub1.sub2.addElement('chb2', SMCheckBox, 'Checkbox 2')
    menu.showTree(True)
    print('\n')
    print(menu.getActualView())
    menu.moveUp()
    print(menu.getActualView())
    menu.moveUp()
    print(menu.getActualView())
    menu.moveUp()
    print(menu.getActualView())
    menu.moveUp()
    print(menu.getActualView())
    menu.moveUp()
    print(menu.getActualView())
    menu.moveUp()
    print(menu.getActualView())
    menu.moveUp()
    print(menu.getActualView())
    menu.moveUp()
    print(menu.getActualView())
    print("\n")
    print(menu)
    print(menu.sub1)
    print(menu.getActualLevel())
    print(menu.getActualView())
    menu.moveInside('sub1')
    print(menu.getActualLevel())
    print(menu.getActualView())
    menu.moveBack()
    print(menu.getActualLevel())
    print(menu.getActualView())
    
